### ISSUE TITLE
Update "Create Pathway" page

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/wikipathways-upgrade#1]
The option to create a pathway with the editor should be removed. It would be good to provide the user with more information about how to create a pathway in PathVisio and upload a GPML file (either through the website or the WikiPathways plugin). 
http://upgrade.wikipathways.org/wiki/Special:CreatePathway

**Comment by AlexanderPico** [comment]
Hmm... Can't seem to edit the page. The edit tab is missing and this link did not produce an editable page:
http://upgrade.wikipathways.org/w/index.php?title=Special:CreatePathway&action=edit

**Comment by AlexanderPico** [comment]
Oh right. This special page content is in php:
https://github.com/wikipathways/wikipathways-upgrade/blob/master/wpi/extensions/CreatePathway/CreatePathway_body.php

**Comment by mkutmon** [comment]
Create pathway page is updated but now the file upload doesn't work anymore. I tried to clean up the "CreatPathway_body.php" file a little more to figure out what's going on, but I am not sure. The form looks okay but I am unsure about the action URL. Currently that is set to http://upgrade.wikipathways.org/index.php. Is that still correct? I know that is was working before the redesigning of the page, so not sure what happened. I will keep looking into it - any hints are welcome.

```
$html_upload = "<FORM action='$this->this_url' method='post' enctype='multipart/form-data'>
                                <table style='margin-left: 0px;'><td>
                                        <INPUT type='file' name='gpml' size='40'>
                                        <tr><td>
                                        <INPUT type='checkbox' name='private2' value='1' $private2> $this->create_priv_msg
                                        <input type='hidden' name='title' value='Special:CreatePathway'>
                                        <input type='hidden' name='upload' value='1'>
                                        <tr><td><INPUT type='submit' value='Upload pathway'></table></FORM>";
```

**Comment by mkutmon** [comment]
Okay ... one step closer. I went back to the old page and started updating Kristina's instructions at the top of the page. The moment I remove the editor radio button option - the upload functionality is lost. 

`<TR><TD><INPUT onclick='showEditor()' type='radio' name='visibility' value='editor' $editor_check><B>Use Editor</B><DIV id='editor' $editor_vis>$html_editor</DIV></DIV>`

I am not sure why that happens yet. Maybe something with the JS scripts related to the radio buttons?

**Comment by khanspers** [comment]
Sorry for breaking the page.....
Do you think it has something to do with the button never getting clicked if its not there? See below. The $uploading parameter presumably never gets set to 1.

line 79: 
} elseif($uploading == '1') { //Upload button pressed
            $this->doUpload($uploading, $private2);
        } else {
            $this->showForm();
        }

**Comment by mkutmon** [comment]
Don't worry. I think it is just cleaning up the code the right way to make sure it works. I got it working for now but the editor option still shows up. If we can hide it somehow that would be fine for now, I guess.
