### ISSUE TITLE
wfMsgExt not present anymore

### ISSUE THREAD

**Issue by nunogit** [wikipathways/wikipathways-upgrade#12]
The function wfMsgExt is not present in mediawiki:

eg.:
http://upgrade.wikipathways.org/w/index.php?title=Special:CurationTags&showPathwaysFor=Curation%3AReactome_Approved

Needs to be  changed according to the documentation

**Comment by mkutmon** [comment]
This is true for a lot of tables used in the Admin Curation Protocol:
- Pathways under construction: http://upgrade.wikipathways.org/w/index.php?title=Special:CurationTags&showPathwaysFor=Curation%3AUnderConstruction
- Tutorial pathways: http://upgrade.wikipathways.org/w/index.php?title=Special:CurationTags&showPathwaysFor=Curation%3ATutorial
- Stub pathways: http://upgrade.wikipathways.org/w/index.php?title=Special:CurationTags&showPathwaysFor=Curation%3AStub
- Curated collection: http://upgrade.wikipathways.org/w/index.php?title=Special:CurationTags&showPathwaysFor=Curation%3AAnalysisCollection
- Featured pathways: http://upgrade.wikipathways.org/w/index.php?title=Special:CurationTags&showPathwaysFor=Curation%3AFeaturedPathway

**Comment by nunogit** [comment]
The function was replaced according to media wiki documentation:

https://www.mediawiki.org/wiki/Manual:Messages_API
