### ISSUE TITLE
Author list missing + port "recent" updates to trunk

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/wikipathways-upgrade#14]
Author list is missing and there were some changes to AuthorInfo files in the past. Some of them might already be implemented in the upgrade version but I can't test it at the moment.

**Comment by nunogit** [comment]
- [x]  Fix javascript (ajax)
- [x]  Check and port code with new author order (author + editors)

**Comment by AlexanderPico** [comment]
I ported the second part since I implemented it. Couldn't pull it to the server, however, as `git pull` gets stuck on a cleanup step. So, still needs testing to confirm...
