### ISSUE TITLE
Keeping repo in sync with test server code

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-upgrade#17]
We all need to pull, commit and push often to avoid conflicts. To see what has been changed locally and not committed or pushed, run `git status`, e.g., these need to be committed:

```
    modified:   ../../../includes/EditPage.php
    modified:   ../../batchDownload.php
    deleted:    AuthorInfoRun.php
    modified:   ../CurationTags/CurationTags.php
    modified:   ../otag/OntologyFunctions.php
    modified:   ../otag/js/script.js
    modified:   ../otag/otags_main.php
```

And we should be able to run `git pull` to pull in changes committed to github (directly or via pull requests). But, currently, if I try this command, I see `Counting objects: 264245, done.` and then it stalls, recommending a cleanup step.  Any ideas?  Should we run the cleanup?  We need to be able to keep our changes in sync with the repo we just started... or start a new one later :)

**Comment by ariutta** [comment]
Any chance it's the Gladstone network? Have you tried it at home?

**Comment by AlexanderPico** [comment]
Tried it at home... not a network lag issue, just a matter of deciding who/when runs cleanup.

**Comment by AlexanderPico** [comment]
And after trying to commit my changes from today I see that the repo is still associated with nuno's personal account, so I don't think anyone else can make commits.

@nunogit @mkutmon Can you guys align the upgrade.wikipathways.org code with the shared repo?  Maybe we should just start a new one?

**Comment by mkutmon** [comment]
It was working fine for us yesterday... I also see commits from you in the repo. After moving the repo to the organization, this linkout (https://github.com/nunogit/wikipathways-upgrade) automatically links to the new repo. So there shouldn't be a problem. 
I made all the changes on the server - before committing you have to set your global user email and user name on the server - it's important to use the global one, so the commits are only connected with your user on the server and not with everyone - then it should work.

**Comment by mkutmon** [comment]
I'll check the local changes in any case - I agree that we should make many commits so there are as little local changes as possible. And I'll try to pull in the changes as well.

**Comment by mkutmon** [comment]
see comments on slack in wikipathways-upgrade channel
