### ISSUE TITLE
WikiPathways Custom Skin

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-upgrade#18]
A lot of good stuff is encoded in our custom skin, called wikipathways. It was a copy of the "monobook" skin with a bunch of custom stuff added. Custom aspects include:
- search box
- hide/show tabs along the top
- loading of script before/after page load
- and much much more

I've begun the port of this content from skins/WikiPathways_old.php over to the new files in skins/WikiPathways/*, but there is more to do or to replace with alternative methods.  

@ariutta, you might want to review the scrip loading in skins/WikiPathways_old.php to see if there is reusable logic or approaches (related to #19).

**Comment by mkutmon** [comment]
committed but needs to be tested

**Comment by nunogit** [comment]
added a couple of files (namely jquery) that were in the old skins/wikipathways/

Note: Ideally jquery location (and other files) should be reorganized (see issue #19 )

**Comment by AlexanderPico** [comment]
As far as I can tell, everything is ported.
