### ISSUE TITLE
What should be in  .gitignore

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-upgrade#29]
I'm finding cases of .gitignore \* (i.e., all files) in a few dirs. I suspect these are part of an older decision and should be removed or updated.  I'll list them below...

**Comment by ariutta** [comment]
Following our discussion regarding what belongs in the directory `extensions` vs. `wpi/extensions`, I added several extensions to the `extensions` directory. Before that, the only extensions in there appeared to be MW extensions that we didn't create.

**Comment by ariutta** [comment]
I think we agree that it's safer to avoid changing MW core code, right? If so, we might be setting ourselves up for success if we avoid including MW core code under version control.

**Comment by AlexanderPico** [comment]
Um... we've already crossed that line by a lot!  Most of the code in the upgrade repo is MW core code that we will never likely edit...  I don't think that's what this issue is about, imho.  If we want to revert this decision, then we're talking about a new repo.  For THIS repo, I'd like to make sure we are including files in a consistent manner, i.e., all the files needed to port the site, with a few noted exceptions (e.g., pass.php, image dir, etc).

**Comment by AlexanderPico** [comment]
Ok. I think I've cleaned this up a bit. All decisions can be reversed, but I went ahead and made a best attempt at consistent logic and unified approach.

Basically, I removed most of the isolated .gitignore files and (when desired) moved the rules to a single, top-level .gitignore

And here's what's in it, now with labels!...

```
# PRIVATE INFO
pass.php

# BIG and BINARY
images/
wpi/data

# AUTO-GENERATED
cache/
wpi/cache/
docs/html

# OLD and TEMP
wpi/tmp/
images.old/
skins/wikipathways_old
```

I also added a bunch of lines based on gitignore standards, including things like lock files and other editor cruft.

And I left a few of the other .gitignore files that made sense and we'll never need to modify, e.g., 
https://github.com/wikipathways/wikipathways-upgrade/search?utf8=%E2%9C%93&q=.gitignore+in%3Apath
