### ISSUE TITLE
Browse List Mode does not work

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/wikipathways-upgrade#7]
http://upgrade.wikipathways.org/w/index.php?title=Special%3ABrowsePathways&browse=Homo_sapiens&tag=Curation%3AFeaturedPathway&view=list

`Fatal error: Cannot access protected property ResultWrapper::$db in /var/www/upgrade27.wikipathways.org/w/wpi/extensions/BrowsePathways/Pager.php on line 312`

**Comment by nunogit** [comment]
Issue solved, one can now list
