### ISSUE TITLE
Download page results in time out

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/wikipathways-upgrade#9]
Not sure what happens in the background but I only see this warning at the end:

`Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/upgrade27.wikipathways.org/w/includes/db/Database.php on line 853`

**Comment by nunogit** [comment]
It's now working. I didn't do anything particular but lolad the page several times.
The lists of links are generated automatically and the zip files also.
I suspect the zip files are created online (when the page is opened). Further investigation to improve the system would be a good idea.
